### ISSUE TITLE
Zoom/Ken Burns effects

### ISSUE THREAD

**Issue by ififfy** [ififfy/flipflip#10]

**Comment by GoddessServant0** [comment]
Done 👍 Reverse effects added

**Comment by ififfy** [comment]
Ken Burns also has panning, so I'm leaving this one open

**Comment by GoddessServant0** [comment]
Did you want just Pan-Left/Pan-Right options in addition to Zoom-In/Zoom-Out?

**Comment by ififfy** [comment]
It would be more of a random pan. A subtle drift.

**Comment by ififfy** [comment]
Yeah, something like that. I'm not sure if it's actually a good idea.

**Comment by ififfy** [comment]
Thinking about this some more, here's what I actually think would be good here: in addition to zooming, users can tell FlipFlip to add a subtle horizontal translate effect with the same duration, covering maybe 10% of the viewport.

**Comment by GoddessServant0** [comment]
So I started this work, and have each of the individual animations working (zoom, trans-horizontally, trans-vertically)... but realized CSS doesn't nicely combine these in any nice way... so I kinda have to define an animation for each combination of options.

I'll implement this for now, but would be nice to clean this up later. Any ideas how to write these in SASS?

**Comment by GoddessServant0** [comment]
Best alternative I could come up with was to use a separate wrapper around the image to do translations ¯\_(ツ)_/¯

**Comment by GoddessServant0** [comment]
Figured out a good alternative using sass loops! See #54
