### ISSUE TITLE
Delete Tags from Sources if removed from Tag Manager?

### ISSUE THREAD

**Issue by GoddessServant0** [ififfy/flipflip#104]
Right now, if a Tag is deleted from Tag Manager, any Sources holding that Tag retain it. However it cannot be toggled on or off if not present in Tag Manager. If a new tag with the same name is added back, the tag is able to be toggled on/off again.

Question is, **do users want to remove all references to a tag if they remove the tag from Tag Manager?**

**Comment by ififfy** [comment]
No opinion for me
