### ISSUE TITLE
Order tags in Library by their order in Tag Manager?

### ISSUE THREAD

**Issue by GoddessServant0** [ififfy/flipflip#105]
Right now, Tags are ordered by the order they were added to a Source. They can be manually re-ordered through the Library, but there is no other sorting options currently. 

**Does it make sense to just sort tags by their order in Tag Manager?** The list inside `LibrarySource` doesn't need to be sorted every time, it could just be rendered in the order Tag Manager uses.

**Comment by ififfy** [comment]
This seems like a good idea.
