### ISSUE TITLE
Future: Remote Sources

### ISSUE THREAD

**Issue by StarrHelixx** [ififfy/flipflip#107]
This is a continuation of our previous work, but to add more remote sources:

- [x] Tumblr
- [x] Reddit
- [x] ImageFap
- [x] Sex.com
- [x] Imgur
- [x] Twitter
- [x] Deviant Art
- [x] Instagram

Sources to Implement:
- [ ] Sharesome
- [ ] BDSMlr

**Comment by GoddessServant0** [comment]
Closing this until this becomes relevant again (neither of these sources are scrape-able at the moment)

**Comment by ItsExtra** [comment]
I'd really like bdsmlr to be available, especially with authentication. It's a very strange site... I have no idea who is running it or even why.... but anyway lots of people are over there. Here is some research I have collected which may or may not be useful toward this end. 

Their support forum has posts [complaining](https://bdsmlr.zendesk.com/hc/en-us/community/posts/360008247160-RSS-Feeds-are-great-but-can-we-get-image-links-wrapped-in-img-tag-) [about](https://bdsmlr.zendesk.com/hc/en-us/community/posts/360009510160-Images-don-t-display-in-RSS-feed) rss feeds, but I can't figure out where the feeds actually are. 

There is another project here on gh called @RSS-Bridge where someone [asked for bdsmlr to be included](https://github.com/RSS-Bridge/rss-bridge/issues/963) but it doesn't look like it got anywhere.

**Comment by StarrHelixx** [comment]
@ItsExtra Thanks for the report! I didn't know they had RSS feeds available! It seems you can access any page's RSS feed by going to `https://<blog_name>.bdsmlr.com/rss` (provided they haven't turned it off for their blog). _And_ it looks like it includes paging so we can actually get all of the images!!! I'm actually super psyched, I've been waiting for them to provide and external way to access blogs for awhile.

This will be implemented and available in v3.1-beta! If I run into any issues, I'll post here.

Thanks again!

**Comment by StarrHelixx** [comment]
Good news! This has now been implemented and is available on the `master` branch! (https://github.com/ififfy/flipflip/commit/0bf3c741f74093632593e5bbe8435fb372582e08) Feel free to test it out and let me know if there's any perceivable issues. 

Please note, that in order for a blog to work, it requires the images be directly available in the RSS feed. You'll notice some blogs do not have them and only have links to each post. Due to JavaScript requirements, scrapers can't access images through those links.

I did find an indexed page in Google for Sharesome API, but it's currently unavailable: https://sharesome.com/developers/rest-api . Closing this issue for now, will check back in the future.
