### ISSUE TITLE
Replace Sortable with React friendly library

### ISSUE THREAD

**Issue by GoddessServant0** [ififfy/flipflip#109]
https://reactjs.org/docs/refs-and-the-dom.html

**Comment by GoddessServant0** [comment]
I tried implementing [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc) and got it working, but it was much worse than the current solution.

* Sometimes tags would not move down to the next row
* If tag was two lines, floating tag was offset weirdly
* OnClick for editing (and changing to an `input`) didn't work.

Sometimes, I do notice lagging when re-arranging Tags. But I can't tell if it is `Sortable` causing this or our implementation.

**Comment by ififfy** [comment]
Drag and drop is React's kryptonite. This is one weird case where I'm OK with not using a React-y library, if the DOM-based one is working well.

**Comment by GoddessServant0** [comment]
It does seem a little laggy with large sets, but there might be something we can do to improve the performance.

However, it definitely performs better than the react-sortable library. I'm going to close this issue. 👍
