### ISSUE TITLE
Automatically add Sources to Library

### ISSUE THREAD

**Issue by GoddessServant0** [ififfy/flipflip#115]
This should be a configurable option.

When a source is added to a scene, it is also automatically added to the Library. It might be helpful to make sure these sources are legitimate and not just "test". This could be done by a simple regex, or (probably better) a `fileExists` or http request.

**Comment by GoddessServant0** [comment]
Meh, I don't like this idea. I'll re-open if anyone requests

**Comment by mute2120** [comment]
I would really like if there were implemented, or at least some way of adding sources from scenes, as I assumed that's how it worked and now I have hundreds of sources in scenes that are missing from my library and no way to add them all.
