### ISSUE TITLE
Debugging: questions/suggestions

### ISSUE THREAD

**Issue by f3lin3** [ififfy/flipflip#117]
I have been banging my head against a brick wall trying to get debugging within the development environment to work. I'd like to be able to:

1.  set breakpoints directly with my development environment on the source code, 
2.  launch FlipFlip (within the development environment),
3.  hit the breakpoint with the ability to edit the source,
4.  save the source,
5.  reload FlipFlip to test the change

I think I have made some progress but would value some insight from you  gurus.. on the following code and configuration style of changes:

### Remove openDevTools()
the present configuration in `main.ts:46`
```
// Open the DevTools.
if (process.defaultApp) {
   mainWindow.webContents.openDevTools();
}
```
I'd like to remove or comment it out (or make subject to optional development environment launch arguments - passed in.)  The reason is that currently automatically launching Electron's debugging tools (which is what the above code does in development builds) appears to get in the way of other development tools (e.g. VS Code ect.) being able to launch and attach their debuggers properly.

The proposed change does not prevent someone from still accessing Electron's debugging tools from within the Flipflip menus if they want it - it just means that they do not automatically appear....

### webpack.config.dev

The current configuration of the `webpack.dev.js` appears suboptimal - because source code mapping is not being included.  I currently understand this to be a mechanism of packing into the source code delivered to Electron a mapping which enables the development tools to track back directly to pre-transpiled Typescript, and thus to also respect breakpoints placed on the TypeScript...

The incantation which I have found works is to add the following into the renderConfig in `webpack.dev.js`

```
    devtool: 'source-map',
    output: {
        devtoolModuleFilenameTemplate: '[absolute-resource-path]'
      }
```

### VS Code

I have only tested this with VS Code - in which I need to create a `launch.json` for launching 
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "electron",
            "request": "launch",
            "name": "Launch Electron against the workspace",
            "appDir": "${workspaceFolder}",
            "sourceMaps": true,
        }
    ]
}
```

At the moment I've not found the incantation to attach the debugger correctly other than putting a 
`debugger;`  line in the code where I am wanting to debug.  This appears to attach the debugger and map directly back to the TypeScript code under the ~/src hierarchy and from that point onwards all breakpoints on tsx code appears to be respected....

I put these changes into a branch https://github.com/f3lin3/flipflip/tree/WebpackConfigTest ... which I will leave up for a few days...

**Comment by f3lin3** [comment]
BTW:  with the proposed changes to `webpack.dev.js`  when I use Electron's debugger I see that webpack has referenced src/renderer/* and that I can be putting breakpoints there on tsx code etc... which did not seem to be there before...

**Comment by GoddessServant0** [comment]
I really have no experience with JS debugging tools (in my limited experience, they have been such a pain-in-the-ass to hook into that I just end up using console prints in stead). So I have really no preference or input concerning whichever tool we use. Personally, the Chrome Dev tools have always been sufficient enough for my purposes.

However, I did want to point out that those `src/renderer/*` docs all already show in the "Sources" tab in Chrome Dev Tools (`webpack:// -> . -> src/renderer -> *`) and break points _already_ work there. However, these breakpoints _don't_ seem work at startup (like when we were porting from pre-v2.0.0). Other than that, I was able to put breakpoints in the code, have them stop, and inspect objects in memory.

**Comment by f3lin3** [comment]
> However, I did want to point out that those `src/renderer/*` docs all already show in the "Sources" tab in Chrome Dev Tools (`webpack:// -> . -> src/renderer -> *`) and break points _already_ work there.

From Chrome Dev Tools perspective:...

Yes they currently do appear there under the "Sources" tab but I would humbly suggest in a rather mangled way... see the screenshot below:  Notice the mangled mess with references to things like `_const__WEBPACK_IMPORTED_MODULE ...`  - look around line 48 - which are obviously not in the original source...

![chrome_dev_current_webpacksettings](https://user-images.githubusercontent.com/46749380/52753154-7fd60d80-2fed-11e9-80ec-558f1cf32931.png)

With the proposed changes to the development version of the webpack a copy of the actual source code - pre mangled is available in addition to the mangled stuff (username was redacted by hand!):  
![with_proposed_webpack_changes](https://user-images.githubusercontent.com/46749380/52753439-887b1380-2fee-11e9-8946-a50c41e0e4d4.png)

And the line numbers match exactly to the source because the source mapping is complete.


With the proposed changes I have been able to step through debugging code in the development environment - make changes directly - which webpack watch picks up - and then reload Electron to pick up the changes...

**Comment by GoddessServant0** [comment]
I totally understand the difference, I wasn't going against your idea. Just giving you the option in the meantime if you needed it 😉

When you do get everything working as you'd like, you should write some usage docs so anyone coming along can easily set it up 😁

**Comment by f3lin3** [comment]
I have submitted a PR for a VS Code Developer Readme - which has more accurate information in it than this thread.  
Contrary to the information above VS Code setup does not require `webpack.dev.js` file to be changed. 

It does however need a developer environment configuration file to be created/edited (launch.json). 

The only point of changing the webpack.dev.js in the manner described above in this thread would be to enable those developers who wish to do their debugging in Electron to be able to have a copy of and step through Typescript rather than webpack mangled TypeScript.

F3
