### ISSUE TITLE
Bug: Overlay Opacity

### ISSUE THREAD

**Issue by f3lin3** [ififfy/flipflip#119]
V2. - Overlay opacity in Scene Details has stopped working properly - .now able to click on slider bar and get opacities of > 100% - eg 9000%

**Comment by GoddessServant0** [comment]
Whoa 😦 Good find, makes overlays broken in beta release .... boo

**Comment by f3lin3** [comment]
I would have liked to have posted the fix as well rather than just identify the problem...
but ... I am using this to refine my remote debugging setup...

Currently able to launch flipflip from the VS Code development environment and do stepping through code in VS Code...  AND can set up Logpoints as well as breakpoints ... 

I will write a setup doc as you suggested...

In passing there is also some really awkward screen re-rendering of Screen Detail when viewing on small screens say 1200x800  - whereby one clicks on a control to edit it and the whole screen redraws the components in different places...  (I'll create another bug for that)

**Comment by GoddessServant0** [comment]
Np, I fixed: fc6b988ed7d8a8f3522ac3e1a9dd10443425c8dc

Thanks for the find f3 😁

Concerning that other issue 🤔 If you could make a small video/gif of what's happening, that'd be super helpful. I use Loom for that kinda stuff: https://chrome.google.com/webstore/detail/loom-video-recorder-scree/liecbddmkiiihnedobmlmillhodjkdmb?hl=en-US

**Comment by GoddessServant0** [comment]
Overlay opacity is working, but overlays still don't seem functional on Mac 🤔

**Comment by GoddessServant0** [comment]
Not sure why, but seems Mac wasn't properly parsing Scene ID. Fixed a73c17669ae13f163f14547e9887cfe279f1b22e
