### ISSUE TITLE
Player Context Menu

### ISSUE THREAD

**Issue by f3lin3** [ififfy/flipflip#129]
I should like to add & change functionality to the Context Menu available in the Player....

If the player's menu is hidden or the player's on top has been triggered, especially in full screen mode then toggling those feature is a matter of recalling the keyboard shortcuts... I should like to add them to the context menu.  However I am concerned that the context menu is already rather large with image related features.  Would it therefore be an idea to put on the context menu a sub-menu - and under the sub menu put essentially a copy of the player menu ?

It the consensus approves I can implement it.

**Comment by GoddessServant0** [comment]
> I should like to add & change functionality to the Context Menu available in the Player

**Can I ask if this is because you personally desired this functionality for yourself when using FlipFlip? Or just a hypothetical user desire?**

I'm of the opinion that most users who use hotkeys learn them and then never need to reference the menu again. This makes a bunch of context-menu options rather redundant (I don't feel like they'll be used much). I'd rather keep the context menu for image-related functions only.

If we do end up doing this, a sub-menu would be the best option.

**Comment by f3lin3** [comment]
Personally I am ambivalent to using menus with a mouse/trackpad as for me the keyboard is much quicker; the mouse simply gets in the way and trackpads are even more frustrating.

However, I would identify that the "Player Controls" menu, the "u-button-row" and the "Context menu" have certain features/commands which might be considered a cumbersome duplication.  

For example:
- "Delete Image" is available on the "Player Controls" menu, a keyboard shortcut, and the Context Menu.
- "Play", "Pause" "Back/Back in Time" "Forward/Forward in Time"  are available on the "u-button-row" and the "Player Controls menu"

The rough edge I perceive is that there are a significant numbers of users who are non-technical. They will interact primarily with the mouse/trackpad and then go hunting and pecking with both index fingers rather than touch typing - especially when needing to use any Control+Key combinations.  Once the application menu is hidden as in full screen mode those users are somewhat at a disadvantage.

Commands on the u-button-row are accessible in full screen mode as the u-button-row as it re-appears when the mouse approaches the top of the screen.

My suggestion - would be to consider rationalizing duplications, and when in full screen mode - either ensure that the Context Menu picked up the Player Controls menu (as a submenu) or that when the mouse approaches the top of the screen the u-button-row AND the menu appears. 

F3

**Comment by GoddessServant0** [comment]
> when the mouse approaches the top of the screen the u-button-row AND the menu appears.

I like that idea the best! 👍 

If we can't implement that, _only_ showing the context submenu (with non-duplicate options) while in fullscreen would be optimal.

**Comment by GoddessServant0** [comment]
#138 Addressed this, but still need to fix hover effect so menu is accessible even in fullscreen
