### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by jacster90** [ififfy/flipflip#134]
unsure if im doing something wrong but, the text will not play from pastebin, hastebin urls or codes nor will a local text file play.

**Comment by GoddessServant0** [comment]
Sorry to hear you're having trouble @jacster90.  It sounds like it might be something on your end or with the url(s) you are trying to use because I know text overlay works, but I'd be happy to help you find the issue. Can you just let me know what version of FlipFlip you are using? Also what hastebin/urls are you trying to use?

**Comment by jacster90** [comment]
I have used 1.1.3, 1.2 and the 2.0 beta all seem not to work.
This is a hastebin url I have tried in the ùrl mode and hastebin mode.
https://hastebin.com/bisukanadu.sql
This is what I entered as the hastebin ID bisukanadu
I have tried this same file just saved as a .txt file to my computer and
selected using the browse files option. the .txt file wasnt open when I
started the Flipflip.
This file I tried from pastebin using the same methods as the last.
https://pastebin.com/FcTBR2rS

Also worth mentioning, I noticed that the 2.0 beta version has a lag when
flipping at a fast speed and shows some gifs for longer than any other gif
or picture at seemingly random times.

**Comment by GoddessServant0** [comment]
Thanks for the response @jacster90. One issue is that hastebin is frequently down, but beyond that, the script you provided worked fine for me. The URL has to be a plain text file, so make sure you are using "https://pastebin.com/raw/FcTBR2rS" as the URL (that's the raw text).

I also wanted to be sure you were aware that the first command is `wait 25000`. This means that nothing is going to show up for 25 seconds after the player begins... Then 3 messages blink, then `wait 15000` (15 seconds)... and so on. Perhaps all the times have an extra 0?

I hope that solves the problem for you, but if you're _still_ not seeing captions, click "View" in the menu bar, and then "Toggle Developer Options" and then click "Console" at the top of the developer options and send us any text from the console that might help us better understand what's going wrong 🙂

You can also try a test file with just ```blink Test1``` to see if captions is working for you or not.
---
Concerning the gifs, I've noticed that issue as well. It's an artifact of us processing the gifs for the number of frames (so we can play the full length of the gifs if desired). I think this is a good thing to try and improve before 2.0 so thank you for mentioning it!

**Comment by GoddessServant0** [comment]
Closing this for now, will reopen if cause of issue is FlipFlip bug.
