### ISSUE TITLE
Bug:  Menu States  Toggle Menu Bar (Off)

### ISSUE THREAD

**Issue by f3lin3** [ififfy/flipflip#140]
I'm sorry our posts crossed in relation to the last Merge, by a minute. 

The menu bar option "Toggle Menu Bar (Off)"   does what it is supposed to in that it sets the menu bar to be hidden.

When then clicking the "Back" button to return to the Scene Details the menu bar is re-enabled.... (So far so good)

BUT if then clicking the "Play" button to play again then the Menu Bar is again displayed - (So far so good as until we can get a clean hover type of function working this is the only way to unhide the menu if the user forgets the accelerator keys)

HOWEVER,  the text on the menu bar is then showing "Toggle Menu Bar (Off)"  rather than "Toggle Menu Bar (On)"

I can have a look at this later on... unless someone beats me to the fix...

F3

**Comment by GoddessServant0** [comment]
🤔 Are you saying that, for you, every time you play a scene it shows the menu bar?

Do I understand your steps right?
1. On SceneDetail Press Play (scene loads with default Menu showing)
2. Click "Player contorls" --> "Toggle Menu Bar..." (menu bar disappears)
3. Click Back (returns to SceneDetail)
4. On SceneDetail Press Play **(scene loads with menu showing again?? -- and menu bar reads icorrectly)**

Because for me, (4) is not showing the menu bar again. And when I toggle it back on (either wisth Ctrl+Shift+6) or by toggling the full screen icon) it correctly shows "Toggle Menu Bar (On)"

**Comment by f3lin3** [comment]
Hi,
1.    On SceneDetail Press Play (scene loads with default Menu showing: *Toggle Menu Bar (On)* ) 
1.   Click "Player contorls" --> "Toggle Menu Bar..." (menu bar disappears: *Toggle Menu Bar (Off)*)
1.    Click Back (returns to SceneDetail)
1.    On SceneDetail Press Play (scene loads with menu showing again?? *Yes*)  BUT when you look at the Toggle Menu Bar item on the menu it says *Toggle Menu Bar (Off)* at this point it should be saying *Toggle Menu Bar (On)*  given that the Menu Bar is on...

**Comment by GoddessServant0** [comment]
Hey @f3lin3, I see your PR and it, indeed, fixes the bug you were reporting.

But I wasn't _trying_ to reset the menu config every time you start the player. As in, I'm not seeing the same behavior as you for (4). For me, the menu bar is still hidden at (4). Must be OS specific for some reason. 

I'll look into this and see what I can figure out. It seems the config is not properly being applied when starting the `Player`

**Comment by GoddessServant0** [comment]
@f3lin3, what OS are you using? Linux? This functionality seems to work correctly on Windows and on MacOS "toggleMenuBar" doesn't seem to do anything at all (which makes sense)

**Comment by f3lin3** [comment]
I'm using Linux.

**Comment by GoddessServant0** [comment]
Can you figure out why [this line](https://github.com/ififfy/flipflip/blob/master/src/renderer/components/player/Player.tsx#L215) isn't behaving correctly on Linux? That's the source of the problem. 

It's supposed to apply the config when the component mounts (and properly does so on Windows/MacOS). Not sure why this isn't working on Linux, and I don't have a way to test myself.
