### ISSUE TITLE
Blurred background delays rendering

### ISSUE THREAD

**Issue by GoddessServant0** [ififfy/flipflip#144]
This was a very minor issue before, but since implementing ImageFAP (which takes a few requests to get images depending on the source type -- i.e. account, gallery, album) I'm really starting to notice a delay between the blurred background image and the player image. This is particularly noticeable with the player on Fast.

The `HTMLImageElement` isn't added to `ImagePlayer` until its `onload` event fires... so we know it's been loaded. `ImagePlayer` renders the image in `ImageView` and also as its own  `backgroundImage` (using `url(<image_url>`) . While I get that means technically there are two requests to the url... from my understanding the browser (in this case Electron) should have cached the image result, so there should be very little time to fetch the image again. Yet, I continually see a blue background on images (particularly gifs) like it's having to load them twice.

@ififfy Any idea what's going on with this or possible fix? 🤔

**Comment by ififfy** [comment]
You could try setting the background image URL as the data URI of the loaded image. It might cause performance problems but you could guarantee it would be shown as soon as it's available.

See the `var dataURL` line in this answer: https://stackoverflow.com/questions/934012/get-image-data-in-javascript

It's just SO MUCH processing for one frame, I think it would probably take 50-100ms, which is like 15-20 FPS.

**Comment by ififfy** [comment]
You could also download every image to a local cache and render from there instead of the original URL, which is probably a better tradeoff and would perform much better. Just bypass the browser cache completely.

**Comment by GoddessServant0** [comment]
> You could also download every image to a local cache and render from there instead

This was the alternative I was considering, but that would also require caching be enabled 🤔 Right now caching downloads images until the cache is full. Maybe I'll shift to an implementation that starts deleting (oldest) images from the cache if the max is reached. We can enable a 500MB cache by default and that should be sufficient 👍

**Comment by GoddessServant0** [comment]
Opting to ignore this for now. Only an issue on a few sites and ultimately  don't favor the forced caching solution.
