### ISSUE TITLE
✨NOTICE: Repository history was re-written (Please re-clone) ✨

### ISSUE THREAD

**Issue by GoddessServant0** [ififfy/flipflip#145]
**05/23/2019**
Please re-clone FlipFlip before making changes.

If you _need_ to keep your current git repo, the following should fix things
```
git pull --force --tags
git fetch --prune
```
You may have local branches or refs which also need to be cleaned up

**Comment by ififfy** [comment]
Why did this happen?

On Thu, May 23, 2019, at 10:15 AM, GoddessServant0 wrote:

> *05/23/2019*
>  Please re-clone FlipFlip before making changes.

> If you *need* to keep your current git repo, the following should fix things

> `git pull --force --tags
git fetch --prune
`

**Comment by GoddessServant0** [comment]
I wanted to replace my name in author field of the git history 😏 lol...
