### ISSUE TITLE
Tagging not working

### ISSUE THREAD

**Issue by LeChninkel** [ififfy/flipflip#146]
I tried tagging with my library. I created about 20 tags, and double clickied on source to start scene, as indicated in the doc. However, no matter how long I hover at the bottom, I never get the tag selector interface.
Is it a bug, or am I missing something ?

thx
M

**Comment by GoddessServant0** [comment]
Hey LeChninkel, sorry to hear you're having issues, that seems odd it wouldn't be appearing 🤔 If you give me some more information I'll do my best to help 👍 First, I'll assume you're running the newest release version (v2.0.0)? Second, can you provide me with your operating system?

When you go to "Tag Manager" you see your tags there right? If so... when you click the name of a source in the Library, you should _definitely_ be seeing them in a sidebar on the bottom...

Another thing that might be helpful is clicking "View" --> "Toggle Developer Tools" and send me anything that appears when you try and load a source from the Library. Maybe there is an error.

**Comment by LeChninkel** [comment]
Hi GoddessServant0! 
thanks for the prompt feedback :) To answer your questions:
Yep, I'm on 2.0.0, and I run on Win10 Pro 1803. And I just realized that, apparently, I simply forgot to hit the "apply" or "ok" buttons after adding all my tags. So basically, none of them had been saved... Major "duh" moment... 😅
So to confir, the tag feature works just fine. And I'm dumb as f***...
Thanks for following up so quickly though ! much appreciated 😉

**Comment by GoddessServant0** [comment]
Lol, no problem. That's just poor design on my part, honestly. The Apply/OK buttons only show up on a few forms, and I've done that same thing 😅
