### ISSUE TITLE
Improve Library Management - Search, Batch Tagging, Import/Export/Merge

### ISSUE THREAD

**Issue by LeChninkel** [ififfy/flipflip#150]
Hello Team :) 
First of all congratulations on the new versions ! Really a wonderful piece of code and so many delightful hours of browsing and exploring... I'm LOVING it ! 
short context description: I have about 3400 sources (3000+ tumblr, 300+ reddit and 100+ local...) 
So I'd like to make a couple of suggestions on making my list of sources more manageable, if I may... :) 
* Multi criteria Source filtering by text string - i.e. "any [untagged] source containing 'family' or 'space', etc." ;)
* Batch Tagging of multiple sources

And a question: I have not tested yet the Scene export for distribution of content, but what would be the effect if I receive a scene export containing remote sources. Would the sources (and possibly even the original associated tags) be imported into my library ? It might be a great idea to also be able to identify Sources that have been added by myself, or coming from Scene Imports... 

Yeah, I'm a bit of a data classification freak... I love to have things stored in little boxes... ;-) 
Thank you SO MUCH for all your efforts. You are really bringing a lot of happiness to folks using your software! I hope we soon start an actual user community emerge and that people start sharing more their scenes and content!
Big hugs
M

**Comment by GoddessServant0** [comment]
Thanks so much for the feedback @LeChninkel! I have a pretty large set of sources myself (but not that big -- yet 😋) so I understand the need for better organization/management. Bulk Tagging (#143) and Library Import/Export/Merge (#142) are already slated for 2.2 release, but I'll go ahead and move tracking those enhancements to this issue 👍 

> Multi criteria Source filtering by text string
It sounds like what you're really asking for is just "search" 😏 Is that right?

> What would be the effect if I receive a scene export containing remote sources?
While Library and Scene share the same "Source" data-structure, tags are currently only present in the Library and are currently removed when the source is imported into a Scene. So if you export/import a Scene it will not have any tag data whatsoever. Similarly "SceneGenerators" are automatically made into stand-alone Scenes upon export/import. This behavior could be changed when Library Import/Export/Merge is implemented.

> Would the sources (and possibly even the original associated tags) be imported into my library?
Currently, no. But this is the hope of Library Import/Export/Merge ability 👍 

> It might be a great idea to also be able to identify Sources that have been added by myself, or coming from Imports...
Any ideas/preference on how to distinguish between them? 🙂

**Comment by LeChninkel** [comment]
hmmm... very interesting points... let's see if I can clarify my meaning :-) 
> It sounds like what you're really asking for is just "search" 😏 Is that right?
Not exactly... Actually my local sources (mostly) have explicit names and a folder tree architecture. Let's imagine I have an external drive plugged and want to use only the sources on that drive, I'd like to enter the Id of the external drive [Disk1] and create a scene using only that source. 
On second thought, I suppose it could be achieved by doing a sort of "search" feature on the source names / tags / types (local, remote, own, imported...) 
The hope, eventually, is to be able to have something that could be used to interact with Sources in bulk, either for Tagging, Deleting, Exporting, adding to Scenes, etc. enter filter to reduce the number of sources, pick all or the ones you want from the subset, and run the desired operation on these. 

The Import / Merge / Export library sounds great !! 

> Any ideas/preference on how to distinguish between them? 🙂

I'm a visual kind of guy... so some kind of icon would be good imho. Maybe the sources should have a table interface, where you could have a dedicated column for "origin" of the source, or type "local, remote" etc. Even maybe include the tumblr, reddit, IG, etc logos in there...

And for your considerations:
> To export local sources? (My feeling is default to no, maybe have a choice)
default to no. Too complicated and dangerous depending on volume of source. I know I wouldn't want to export my 10'000+ pics local collection of kittens as a source...
> Allow choice for overwrite/merge or just merge? I'd say both. You may want to overwrite the external scene with the latest version. 
> How to import tags? Do we just add to existing tags? What if two are very similar and user wants to merge them? (e.g. Kittens vs Cats) I suggest "import by adding to existing" and let the end user rename/replace the ones he doesn't like... Too hard to work out the semantics with "cats vs kittens" imho.

hope it helps :-)

**Comment by GoddessServant0** [comment]
> It sounds like what you're really asking for is just "search" 😏 Is that right?
> Not exactly...

Can you think of a use-case that search _doesn't_ fulfill? For instance, if you're searching for a certain drive or directory, you could just search "I://" or "I://Pictures/" and you'd see just those sources. This could even include filters like "I://Pictures/*.gif".

> Any ideas/preference on how to distinguish between them? 🙂
> I'm a visual kind of guy...

Okay, I think I'll add an indicator to the right (near ✏️ and ❌) for type and original/imported.

**Comment by LeChninkel** [comment]
> Can you think of a use-case that search doesn't fulfill? For instance, if you're searching for a certain drive or directory, you could just search "I://" or "I://Pictures/" and you'd see just those sources. This could even include filters like "I://Pictures/*.gif".

yeah, was just thinking about that... Beyond the "search", I think what I also mean is that I'd like to search by source properties. i.e. Local vs IG vs Reddit vs Tumblr vs own vs imported vs ... etc. ON TOP of text search. if there is a n "advanced Search" including easy properties of sources akin to Tags, but without having to add them individually, I'd be a happy chappy :) (I could obviously add a "IG" tag when bulk tagging is implemented, but from an end user perspective it would be cumbersome to do this manually when it could be included in a filter criteria... ;) )

**Comment by GoddessServant0** [comment]
Couldn't you just search "reddit.com", "tumblr.com", "instagram.com" too then? 🤔 I was thinking of introducing a search feature, and you could still use the current tag filtering _on top_ of that. I want to make sure I'm fulfilling what you're looking for, but no need for extra work if search can do that already 👍

**Comment by LeChninkel** [comment]
Actually, you're absolutely right. If the Search functionality allows for multiple criteria, like "tumblr +sexy -blonde" i.e. "contains tumblr and sexy, but NOT blonde" than I am more than happy 👍😊

**Comment by GoddessServant0** [comment]
TODO:
---
- [x] Implement search
- [x] Batch Tagging
- [ ] Don't strip tags from scenes
- [ ] Add ability to import into library when importing scene
- [ ] Library Export
- [ ] Library Import
- [ ] Add types to Sources (original vs import)
- [ ] Add filter for imported
- [ ] Implement negative search filters

**Comment by LeChninkel** [comment]
ooooh joy !!!! thanks for the update ! 😍

**Comment by GoddessServant0** [comment]
Done 😁 This stuff will be in the next release, but if you'd like to try it early, you can always checkout the head of [`master`](https://github.com/ififfy/flipflip/commits/master)
