### ISSUE TITLE
Time for a proper HTML user manual?

### ISSUE THREAD

**Issue by ififfy** [ififfy/flipflip#152]
Our GitHub wiki page is pretty long at this point. It would be nice to have something more browseable. There are lots of Markdown-to-web-site tools out there.

**Comment by GoddessServant0** [comment]
How would this be hosted? Are you thinking an in-app manual?

**Comment by ififfy** [comment]
Github Pages

**Comment by GoddessServant0** [comment]
This has been completed, you can see test at https://goddessservant0.github.io/flipflip/#/

Or https://ififfy.github.io/flipflip/#/ if this has been merged in
