### ISSUE TITLE
I lost 20 minutes of tagging because the library didn't save

### ISSUE THREAD

**Issue by ififfy** [ififfy/flipflip#153]
I tagged a bunch of sources and then quit the app. When I reopened it, all my tags were gone. I quit directly from the library.

**Comment by ififfy** [comment]
I just tried this again:
* Add 4 sources
* Open each one, add a tag
* Navigate back to the top screen
* Wait a few seconds
* Quit and reopen
* ...those 4 sources are missing

**Comment by GoddessServant0** [comment]
🤔🤨 Hmmmmm...... I'm unable to reproduce this on Windows _or_ Mac. Are you running from dev-tools or from release executable (I tried both, but both worked)? Do the sources disappear or the tags?

**Comment by GoddessServant0** [comment]
This appears related to #151 , issue was not present before merge. 

Can confirm after PR, route is not always properly restored

**Comment by GoddessServant0** [comment]
Because #151 bound `this.state` to `appStorage.save` when mounted, it only ever saved _that_ `state`.

This was fixed (https://github.com/ififfy/flipflip/commit/dd8e0deeddf1e2c1411082e0cb2902590b4ca0b0) to always send the _current_ `state.

Let me know if this didn't fix it 🙂

**Comment by ififfy** [comment]
Of course I did it to myself lol. You can revert the commit if you want and I'll try again.

**Comment by GoddessServant0** [comment]
Your email missed my follow up message 😋 This was fixed (dd8e0de) to always send the `current` state.
