### ISSUE TITLE
Support more video formats

### ISSUE THREAD

**Issue by StarrHelixx** [ififfy/flipflip#160]
[From Reddit](https://www.reddit.com/r/flipflip/comments/c9gjz5/an_idea_for_aviflv_support/)
So what if there were Avi/Flv support and the ability to layer videos over another? Avi & Flv Support transparency.

If this was a feature, when audio support for videos are added, you could theoretically overlay a song + beatmeter .avi or .flv ontop of a video, gif, or picture slideshow. This'd allow for custom slideshows and be a neat feature for flipflip.

---
This will require using a video library for additional support. This will likely add additional complexity to style/effects.

**Comment by GoddessServant0** [comment]
[Video.js](https://videojs.com/) supports FLV at least, but any other codecs would have to be transcoded on the fly.

**Comment by ififfy** [comment]
"On the fly" means "on the CPU in JS," which is a non-starter.

**Comment by ififfy** [comment]
What you could do, if you were really fancy, is design a special video server that transcodes like Plex, but it'd be a nightmare to distribute cross platform and bundle with the app.

**Comment by GoddessServant0** [comment]
> "On the fly" means "on the CPU in JS," *which is a non-starter.*

Exactly what I was thinking...

I might look into implementing VideoJS for FLV support, but only if overhead is very minimal.
