### ISSUE TITLE
option to play "Videos only" from mixed source folder ?

### ISSUE THREAD

**Issue by LeChninkel** [ififfy/flipflip#161]
Hey there :)
I LOVE the latest release !!! The ability to play videos and the randomization options are just AWESOME ! 
I was looking for something though that I thought was obvious, but couldn't locate. There is a "play gifs only, play stills only, play all images" option. Is there a "play videos only" option for source folders that may have mixed media...? 
thank you again for all the hard work... This is really a masterpiece. :)

**Comment by LeChninkel** [comment]
ok nevermind... realized the "play gifs only" includes videos ;)

**Comment by GoddessServant0** [comment]
Still a good idea! I should add a separate option, ty @LeChninkel 😉
