### ISSUE TITLE
possible bug - lost Tag list

### ISSUE THREAD

**Issue by LeChninkel** [ififfy/flipflip#164]
Hey :)

I was playing with my library, tagging stuff, and decided to add a new tag. As I entered the name, I dragged it to sort alphabetically. And when I released, I only have not blank tiles... and all my tagging of my sources seems to have disappeared...

Has anybody seen this happen ? 
![image](https://user-images.githubusercontent.com/44675141/61496044-4bf77d80-a9bb-11e9-8ea7-35754125e062.png)

**Comment by GoddessServant0** [comment]
😳 Woah.... that's... strange.... (I hope you had a backup 😫 -- Or just hit back instead of OK) 

Luckily I was very easily able to recreate this >.< Apparently this happens if you ever make a tag and then try and move it without hitting ok and then coming back to tag manager.

I'll release a bug fix for this (and anything else that might arise) on Monday

**Comment by LeChninkel** [comment]
oh my... 😅
Well no, no backup... That's about 600 tagged sources down the drain... oops ! 😂😂😂And I did actually hit "back", and not OK... I think... 🤔🤣 Ah well, it happens, and I guess I've learned my lesson. No big harm done. I've had fun tagging my sources. I can have more fun doing it again! 😉

Regarding backup, I actually did not see any such feature in the app, so I guess I just need to make a copy of the data.json file? Alternatively, I'll just archive the whole folder... 😊

Thank you for looking so quickly into this! I'll be looking forward for the next version with the fix. 
M

**Comment by LeChninkel** [comment]
Exploring a bit further, I started rebuilding my Tags list. Even after saving the list, moving a tag to reorder makes all tiles go white. 
I also tested the behavior with an empty data.json file, and the behavior is consistent. Any reordering of tags will result in white tiles. And hitting "ok" will finally remove all tags... 

![image](https://user-images.githubusercontent.com/44675141/61514264-ef6a8180-a9ff-11e9-906d-fe5378761cd4.png)

**Comment by GoddessServant0** [comment]
> Well no, no backup... That's about 600 tagged sources down the drain...

NOOOoooooOOOOooo!! 😭 Awwww I'm so sorry... still 600 is _a lot_ of work you don't want to have to redo.... blurg... 😫

> I actually did not see any such feature in the app

In preferences, near the bottom is a "Backup/Restore" section where you can create and restore backups,. check it! Maybe yours was backed up automatically! 

> Any reordering of tags will result in white tiles.

Yup, I confirmed you are totally right, I severely broke that in the last update... I'll have a fix rolled out soon. But I was at least able to confirm that if you just hit "Back", nothing bad happens 👍

**Comment by GoddessServant0** [comment]
FFUUUU****KKK This also happens if you re-order scenes!!! Don't do that!

**Comment by GoddessServant0** [comment]
Fixed this and will have a new release published by this afternoon 👍

**Comment by GoddessServant0** [comment]
Fixed bab719f189ef9ec9211dc31fa5082be6cd4ab703

Releasing `v2.3.1`...
