### ISSUE TITLE
Welcome Guide / Material Design Re-Design?

### ISSUE THREAD

**Issue by StarrHelixx** [ififfy/flipflip#174]
I've been told more than once that a help guide which walks the user through using FlipFlip might be helpful.

The wiki serves this purpose to an extent, but a set of prompts which direct users how to use FlipFlip the first time they open it might be useful. Animated and interactive, even better.

**Comment by GoddessServant0** [comment]
I know one of our original goals was to maintain this ... "Windows 95" aesthetic 😋 But I've really been wanting to make a more modern UI for awhile. Personally, I'm a fan of [Material Design](https://getmdl.io/) which is pretty easy to implement. Any objections?

**Comment by ififfy** [comment]
It's not Windows, it's BeOS! Even more obscure. :-)

At this point I see the way the wind is blowing. Nobody but me likes the current aesthetic and I haven't contributed in a while, so I should let you move on to something that makes sense to you.

Personally I don't love the look of Material Design, but I understand it has a lot of advantages and I don't object. I hope you'd use a pre-packaged set of components like [Material UI](https://material-ui.com/).
