### ISSUE TITLE
Let user choose to pick images from entire image set, not by directory first

### ISSUE THREAD

**Issue by ififfy** [ififfy/flipflip#2]
Please comment if this actually matters to you. I might not bother if no one does.

**Comment by LeChninkel** [comment]
Personally, I am not really interested in this. If I want a subset of certain images, such as favorites, or by themes, I just add them into a specific directory and I'm done. I do not expect Flipflip to become a "picture manager" with flagging or a sort of grid selection UI. I organized my pictures by directory/subdirectories like this:
Theme 1 (Scene 1) 
   |----> Subdirectory 1
   |----> Subdirectory 2
Theme 2 (Scene 2) 
   |----> Subdirectory 3
   |----> Subdirectory 4
etc.

And I did this using other "picture management" tools. The issue I have is that those picture managers have very slow slide-show features, that do not play well with huge image libraries. So Flipflip works beautifully to fill that gap. 
In essence, Flipflip is for me the perfect substitute for the infamous "gooninator" for local files. And I use it as such.
But maybe I am not understanding the question correctly ? Let me know if that helps or not.

**Comment by ififfy** [comment]
No one has asked for this so I'm closing it.
