### ISSUE TITLE
Decide whether to have an RSS feed of releases or something

### ISSUE THREAD

**Issue by ififfy** [ififfy/flipflip#20]
Feels weird to just post about this in certain places on Reddit.

Maybe a forum? A dedicated subreddit?

**Comment by GoddessServant0** [comment]
Yea! I'd be down for a dedicated subreddit where we can drop patch notes and stuff. Cross post to hypno reddit if we feel like it 👍

**Comment by ififfy** [comment]
I created https://reddit.com/r/flipflip
