### ISSUE TITLE
All my Scenes are gone

### ISSUE THREAD

**Issue by talmakprime** [ififfy/flipflip#203]
I used flip flip earlier today I close it as I always do when I came back to it all my 40+ scene where gone

**Comment by StarrHelixx** [comment]
😣 I'm sorry to hear that! Unfortunately, FlipFlip data can get corrupted. However, it does save backups when it updates as well as when manually backed-up. If you go to Settings, you should see "Restore Backup" option. Hopefully this helps, as I completely understand the frustration of losing all that (it's happened to me as well).

**Comment by StarrHelixx** [comment]
Closing this
