### ISSUE TITLE
Export to MP4

### ISSUE THREAD

**Issue by StarrHelixx** [ififfy/flipflip#205]
This has been highly requested, but I'm not sure how to accomplish it in the end. I've previously attempted to use Electron's window capture capabilities, but it was very choppy and I couldn't get the audio to correctly work.

**Comment by StarrHelixx** [comment]
See [this tutorial](https://ififfy.github.io/flipflip/#/screen_capture)

**Comment by ififfy** [comment]
I'd also point out that you can do this in Quicktime Player on Mac for free without installing anything.

**Comment by StarrHelixx** [comment]
Closing this
