### ISSUE TITLE
most recent 3.2 version is blank

### ISSUE THREAD

**Issue by Soriq** [ififfy/flipflip#206]
![blank flipflip](https://user-images.githubusercontent.com/59146258/71325522-aa1d1500-24b3-11ea-854d-5a203bbb11e6.png)

Was working well but now when I open the program it only shows this page.

**Comment by Soriq** [comment]
windows, tried both 32 and 64 bit

**Comment by StarrHelixx** [comment]
Hey sorry you're having problems with the new version. Sounds like there was an issue with migrating data from whatever previous version you were on. Do you happen to remember which version you had before 3.0.2?

Also, if you click "View" and then "Toggle Developer Tools" and then make sure you're on the "Console" tab... do you see any errors printed there? That would be the quickest way for me to diagnose and fix the issue 👍

**Comment by Soriq** [comment]
Thanks. It's actually my first time using flip flip yesterday so no
previous version. Here are the errors that came up
[image: flipflip errors.png]

**Comment by Soriq** [comment]
I deleted the json data file just to see what would happen and sure enough
seems to be working now.
