### ISSUE TITLE
Randomize caption lines

### ISSUE THREAD

**Issue by Alsweider** [ififfy/flipflip#208]
If you have a longer list of captions, it would help to have an option to randomize the caption lines just like the pictures.

**Comment by StarrHelixx** [comment]
You can do this already via the [$RANDOM_PHRASE](https://ififfy.github.io/flipflip/#/caption_script?id=random-phrases) command.

Does that fulfill your needs?

**Comment by Alsweider** [comment]
> Does that fulfill your needs?

Exactly what I had in mind, thank you. I must have missed the subsections the first time.

**Comment by StarrHelixx** [comment]
> Exactly what I had in mind, thank you. I must have missed the subsections the first time.

No problem 😁
