### ISSUE TITLE
blink $RANDOM_PHRASE

### ISSUE THREAD

**Issue by m----r** [ififfy/flipflip#212]
The output of below is "kittens / are / cute". Would like it to instead be "kittens" "are" "cute"

> storePhrase kittens / are / cute
> blink $RANDOM_PHRASE

Hope this makes sense. Thanks!

**Comment by StarrHelixx** [comment]
Thanks for this suggestion! This has been implemented: 9687299129aca9f643218bb8d0e5dc1596728150
