### ISSUE TITLE
Fix for the sex.com issue 

### ISSUE THREAD

**Issue by nrop4nrop** [ififfy/flipflip#214]
Hello community

I was wondering why sex.com was not working so checked it out. 
To reproduce:

1. get a image link (from here on the [LINK]) it should have somting with cdn in it. 
2. curl the url. you will get a something like this <html><head><title>403 Forbidden</title>....
3. use the same curl command but add -H "Referer: https://www.sex.com" --output test_download.jpg
4. verify the image

So the issue is the missing referer. As my js skills are beyond awful and my nvm is broken. I thought I just leave it here so maybe someone feels like fixing it in the code. 

Anyway great software and thanks.

**Comment by StarrHelixx** [comment]
That's definitely the problem, but it is, unfortunately, not possible to manually set the `Referer` header when making a request in JavaScript 😕 And none of the hacks I found work in the version of Chromium being used by Electron.

If someone is aware of a way to spoof the `Referer` header, please do let me know, but I believe this is a long shot.

**Comment by StarrHelixx** [comment]
This isn't possible until they provide a public API (this is also discussed often on Reddit). Closing for now
