### ISSUE TITLE
Image sizing ideas for portrait

### ISSUE THREAD

**Issue by m----r** [ififfy/flipflip#215]
This is my brainstorm based on how to handle portrait videos without rotation:

- Tile from left/right. 
   - Fit video height
   - Display the video at the left/right edge
   - Repeat the video until there is not enough screen space

- Mirror horizontally.
   - Fit video height
   - Display the video at the left edge
   - Beneath the video, display a horizontal-flipped version at the right edge

- Display at edges.
   - Fit video height
   - Display the video at the left edge
   - Beneath the video, display the video at the right edge

Since these first fit height, there may be some clipping and/or overlapping wonkiness, especially for landscape videos.

**Comment by StarrHelixx** [comment]
Closing this, as cloning video is not trivial. This will eventually be part of upcoming grid improvements, but there are no plans to support "Tile" view
