### ISSUE TITLE
Integrate with Hydrus

### ISSUE THREAD

**Issue by StarrHelixx** [ififfy/flipflip#222]
[From Reddit](https://www.reddit.com/r/flipflip/comments/fkfdmc/is_integration_with_hydrus_a_possibility/)

**Comment by PupBrutus** [comment]
Any bonus points if there is already a nodejs module for it?

https://github.com/cravxx/hydrus.js/

**Comment by StarrHelixx** [comment]
This is done: https://github.com/ififfy/flipflip/commit/16ab4c0bde5ac0b02ff5ccf1e1a3a5d1b12874d9
