### ISSUE TITLE
Cross-fade and zoom look weird together

### ISSUE THREAD

**Issue by ififfy** [ififfy/flipflip#223]
I just ran through the tutorial. This issue can be seen in the scene the tutorial creates.

The zoom timer should extend to cover the cross-fade period, otherwise the image stops zooming in a jarring way.

**Comment by StarrHelixx** [comment]
I can see a use case for _wanting_ to stop the zoom early with fade, so I wouldn't want to assume to add cross-fade time to the transition effect.

However, I fixed this in the tutorial to use a greater time and suggest creating a buffer of time when using zoom in tandem with crossfade: https://github.com/ififfy/flipflip/commit/7f4b39083a10a8899caa6faf4a5b94713bc6c7ab
