### ISSUE TITLE
Program froze during introduction-won't go away even after refreshing,restarting,redownloading

### ISSUE THREAD

**Issue by biteboy** [ififfy/flipflip#227]
Hi, I've downloaded the file for the 32bit windows program and have run into an oddly persistant problem during the introduction. The program seemed to have been working fine up until this point but at a certain stage it froze on this screen.
![image](https://user-images.githubusercontent.com/64456065/80449080-315c1880-88ec-11ea-9b69-d69a10fccf15.png) -hopefully that worked, i've never used github before

I've tried to all the functions at the top, including the refresh and hard refresh, but they haven't changed anything. I deleted the folder and extracted the zip again to hopefully replace the program but that changed nothing. Restarting my computer and running the .exe after it woke up didn't work either, whatever I do the program remains frozen on that one screen. 

I'd assume that redownloading the program should've at least reset it back to how it was when I first started it but I guess that wasn't the case, does the program store something anywhere else on my computer that it's reloading that state from? Any help would be appreciated, I'll add onto this if I manage to fix it myself, thanks!

**Comment by StarrHelixx** [comment]
hey @biteboy, sorry you ran into this issue. I'm not sure what prevented the tutorial from re-loading, but I'll look into that.

You're right that FlipFlip stores its data outside of the installation. All of your FlipFlip data is stored in a file called `data.json`. You'll find this file at `C:\Users\<user_name>\AppData\Roaming\flipflip\data.json` on Windows or `/Users/<user_name>/Library/Application Support/flipflip/data.json` on Mac. You can just delete it to reset FlipFlip. Just for reference, this is also the directory where backups are saved and where you'll find the default image cache.

**Comment by biteboy** [comment]
Ah thanks, I was able to successfully reset the program. In case anyone else has this problem just gonna mention that the Appdata folder might be hidden, so you'll have to enable viewing hidden files if you haven't already.
