### ISSUE TITLE
Every 500ms data.json is saved on Disk

### ISSUE THREAD

**Issue by katzlbt** [ififfy/flipflip#228]
Every 500ms (see comment #211) data.json is saved on Disk this causes 24*60*60*2*20kB to be written to disk per Day (24h) of use of the program. That is 3.5 GB useless data written to the SSD (The OS cannot skip a single write operation to the SSD by caching it!).

Combined with the screenlock-disable this can write through your SSD free space once every few months and burns useless energy. I better wait for a fix.

**Comment by StarrHelixx** [comment]
This has been fixed: https://github.com/ififfy/flipflip/commit/3da8cfbf5a1a484be3d8e9324ba14c4c101b27af
