### ISSUE TITLE
E621 no longer working.

### ISSUE THREAD

**Issue by diafggl** [ififfy/flipflip#234]
e621.net used to function in flip flip but it seems it no longer does, it may have to do with the sites new overhaul.

**Comment by StarrHelixx** [comment]
Looks like they updated their site back in March to require you login in order to access their API. I might add this later, but in the mean time, I'd recommend using a tool like https://github.com/Bionus/imgbrd-grabber to download images, and then use FlipFlip to load them directly.

**Comment by StarrHelixx** [comment]
E621 now has it's own source implemented and is working again: https://github.com/ififfy/flipflip/commit/8bf4200f0aa32f905b479f1151f50c44dc0dfef4
