### ISSUE TITLE
Feature request: sync captions with scene

### ISSUE THREAD

**Issue by rwjmiller** [ififfy/flipflip#236]
It would be nice to have a way to override all the caption script timing options and tell flipflip to display the next caption on top of the next image, the same way that the various other 'with scene' timing options work (e.g. for strobe and audio playback).  This would be particularly useful for scenes that use wave mode timing as the intervals are constantly changing.

Is there any way of doing this with the current caption script parameters? If not, is this something that could be added?

**Comment by StarrHelixx** [comment]
This will be part of the upcoming [Audio/Caption Improvements](https://www.reddit.com/r/flipflip/comments/eoqe1q/community_input_upcoming_audio_and_caption/) work. Unfortunately, no timeline on when these features will be done, but they are currently what I'm working on 👍

**Comment by StarrHelixx** [comment]
This has now been implemented! Closing issue
