### ISSUE TITLE
Full length video ignores speed settings

### ISSUE THREAD

**Issue by Kivip** [ififfy/flipflip#239]
If you have selected to play videos in full the total play time is set to the actual length of the video, and ignores any speed multipliers, set or random, that are applied to the playback. This makes slowed videos switch prematurely, and sped up ones to replay the beginning.

**Comment by StarrHelixx** [comment]
Lol, I can't believe I overlooked this, thank you for reporting!

**Comment by StarrHelixx** [comment]
This has been fixeed: https://github.com/ififfy/flipflip/commit/fcd2790625ebea19ebf6f422d079db2654f9f7f5
