### ISSUE TITLE
Issue: captions do not load when the same captions file is used for two consecutive scenes

### ISSUE THREAD

**Issue by rwjmiller** [ififfy/flipflip#242]
If one scene follows another and both use the same captions file, it isn't loaded when the second scene starts.

**Comment by StarrHelixx** [comment]
I wasn't able to reproduce this issue 😕

I observed the following:
* When two consecutive scenes have **the same** Script URL, the caption script **continues where it was** when the next scene starts
* When two consecutive scenes have **different** Script URLs, the caption script **starts from the beginning** when the next scene starts

Are you experiencing something differnet @rwjmiller and are you on the most recent release?

**Comment by StarrHelixx** [comment]
Closing this for now. 

@rwjmiller, if what I posted above doesn't match your observations, please provide instructions for recreating this.
