### ISSUE TITLE
3.1.0 Beta - BDSMlr(?) RSS Feed 500 Error Status Handling

### ISSUE THREAD

**Issue by professor-mesmerize** [ififfy/flipflip#244]
Found a good ol' beta bug! Or, well, maybe more of a BDSMlr bug to take into account when importing BDSMlr RSS feeds than an actual FlipFlip bug.

I've discovered (through some unnecessarily extensive testing of the RSS feeds of my BDSMlr blogs and sideblogs) that, sometimes, certain "pages" of a BDSMlr blog's RSS feed will return an HTTP 500 error response - even when most of the pages return the RSS feed just fine. 

As a (fake) example:
https://mycoolblog.bdsmlr.com/rss?page=1 returns a 200
https://mycoolblog.bdsmlr.com/rss?page=2 returns a 500
https://mycoolblog.bdsmlr.com/rss?page=3 returns a 200
...etc, etc

Currently, it appears that FlipFlip handles 500 errors in BDSMlr RSS feeds in one of two ways:

1. If the first "page" of **any** BDSMlr RSS feed Source in a Scene returns a 500, FlipFlip gets stuck on the "loading screen" for the source/scene.
2. If the first "page" of **all** RSS feed returns a 200, FlipFlip appears to iterate through the pages importing images (woo!) until it hits a page that returns a 500, at which point it seems to stop iterating through the pages (less dope) and just continues running the scene with the images it's already loaded

(Note: I haven't tested if RSS feed errors are handled similarly with non-BDSMlr RSS feeds, primarily because I didn't know of another supported RSS feed to try.)

While I have a support ticket out to BDSMlr regarding the weird 500's for some pages of the RSS feed and not others, it's likely that some blogs will always get 500's for some pages of their RSS feed (mainly because it appears that the RSS feed for each item is generated once, based on how some older blog's RSS feeds don't have <img> tags in their feeds, which was a somewhat recently implemented enhancement). 

Therefore, feature request! Could we update the error handling of the BDSMlr RSS feeds to "skip" to the next page of a BDSMlr RSS feed if the a specific RSS page request returns an error? That would at least address the #2 scenario above, and could potentially also address the #1 scenario as well. (I'm actually not sure how scenes currently handle other remote source loading failures, but potentially that could be applied here instead/in addition to?)

Otherwise, things look great in this beta! Was super excited to see BDSMlr support added, and I'm really liking the Easing features. Thank you for all the love and hard work y'all pour into FlipFlip!

**Comment by StarrHelixx** [comment]
Hey thanks so much for the (very detailed) bug report! 

I can definitely update the behavior to continue checking until 0 results are found for a page, and prevent dying when a 500 response is returned. Right now, BDSMlr is the only "RSS" type source, so there's nothing to really compare it to in FlipFlip.

Overall really wish they would add a damn API 🙄 But maybe in time.

**Comment by professor-mesmerize** [comment]
@StarrHelixx Gods, same. 😂  Though, honestly, at this point I'd settle for an even slightly more modern and standardized form of authentication!

**Comment by StarrHelixx** [comment]
Okay, I've modified the BDSMlr loader to retry 3 times before giving up on a source. This should resolve your issue.
