### ISSUE TITLE
3.1.0 Beta - BDSMlr feed issue

### ISSUE THREAD

**Issue by echoistheft** [ififfy/flipflip#248]
Hi,

I am testing 3.1.0 Beta to access  BDSMlr via RSS.  For whatever reason, no matter what URL I enter I get the images from the first page of the feed.

i.e. if i have https://demoblog.bdsmlr.com/rss?page=12 I only seem to be getting the https://demoblog.bdsmlr.com/rss?page=1 images.

I'm on MacOS Big Sur, if thats useful.

Any ideas?

Thx,
EQ

**Comment by StarrHelixx** [comment]
If you are trying to only play a certain _page_ of a feed, that is not possible. In fact, if you truly entered `https://demoblog.bdsmlr.com/rss?page=12` as a source, those URL's probably aren't working, and FlipFlip is just playing the images you have cached. But a generic url (e.g. `https://demoblog.bdsmlr.com`) entered into a Scene will play all of the images of that feed, starting with the 1st page. 

I've just confirmed on my copy of `v3.1.0-beta1` that entering and playing `https://tiendadelputaria.bdsmlr.com/` successfully downloaded images from all pages. If you are experiencing different behavior, I'd need a better way to reproduce the problem. Feel free to DM me on Reddit if you prefer privacy 🙂

**Comment by echoistheft** [comment]
I literally just saw that on the Reddit page. I'm so used to having to put https://demoblog.bdsmlr.com/rss into a feed fetcher that the idea of not including the /rss never occurred to me. Might be something to add into the docs.

And I am able to grab the feed w/o the /rss 

D'oh.

Thanks.
EQ

**Comment by StarrHelixx** [comment]
No problem! I've fixed BDSMlr addresses to work with `/rss` suffixes since beta1. This fix will be available in `v3.1.0-beta2` which should be out in the next  day or two
