### ISSUE TITLE
FlipFlip Crashes When Trying to Use Hydrus URL That Doesn't Contain 'tags' Query Arg

### ISSUE THREAD

**Issue by professor-mesmerize** [ififfy/flipflip#251]
### Description
Pretty much what it says on the tin! It appears that when a Hydrus source doesn't have the `tags=` query parameter, and that source is either previewed or used in a Scene, FlipFlip gets, uh, real sad. The screen goes completely white immediately, and Reloading or Force Reloading does nothing. Even wilder - FlipFlip will continue to display that white empty screen _even after quitting and restarting it_. 

It appears that the bug, in addition to crashing FlipFlip, somehow corrupts the `data.json` file!

So, good Hydrus URL:
`http://localhost:45869/get_files/search_files?system_archive=true&tags=["mesmerizing"]`
Bad Hydrus URL:
`http://localhost:45869/get_files/search_files?system_archive=true`

The Hydrus Client API documentation on `/get_files/search_files` specifies `system_inbox` and `system_archive` as optional, while it's silent about `tags` being required, so it's super reasonable to assume `tags` is required. 

But, in testing on my local Hydrus server, I found that the response JSON is identical for each of the above URLs, so I'm guessing this has something to do with FlipFlip relying on `tags` query arg being there - which, see above, is probably fair! I'm not sure if the documentation is outdated or if queries without the `tags` argument just sort of work by accident, but they do seem to work!

That said, I figured I should report this bug anyway, because the crash itself is so egregious and permanently effs up your `data.json` file, that I figure you'll probably want to add some error handling to the code that handles Hydrus URLs, regardless of whether you want FlipFlip to support Hydrus URLs without `tags` arguments. 😅 

### Deets
**Versions:**
- v3.1.0-beta2

**Settings Options**
 - Portable Mode Enabled

**OS:**
- macOS 10.15.7

### Screenshots:
_Right After Previewing Hydrus Source w/out tag query param_
![SourceAddedPreviewButtonClickedWhiteOut](https://user-images.githubusercontent.com/65079055/107601199-03825f00-6bf4-11eb-807b-0056abeaf381.png)

_Restarted FlipFlip After Previewing Hydrus Source w/out tag query param_
![QuitAndReloadFlipFlipWhiteOut](https://user-images.githubusercontent.com/65079055/107600993-66bfc180-6bf3-11eb-9ace-1076d6cb408e.png)

### Attachments:
`data.json` file that's corrupted after using bad Hydrus Source: 
[baddata.json.txt](https://github.com/ififfy/flipflip/files/5963071/baddata.json.txt)

### Repro Steps

1. In Settings, set to Portable Mode (may not be needed! I didn't test without it)
2. Authorize Hydrus Server in Settings
3. Add Hydrus source without `tags` query param. Example: `http://localhost:45869/get_files/search_files?system_archive=true`
4. Attempt to preview source by clicking on thumbnail OR add source to scene and play scene
5. After getting whiteout screen, quit FlipFlip completely, and then reopen it. You should see the same white screen.

**Comment by StarrHelixx** [comment]
Thanks again for such a detailed bug report! I pushed a fix for this issue: https://github.com/ififfy/flipflip/commit/a46a32656431dfc6a6bb848b532fc91e6d7a4f4a

I fixed the Hydrus regex to only match if the URL contains `tags=.*`, but is there a reason you can think of to _not_ include tags? (I don't use Hydrus, so I'm unfamiliar with the different use-cases)

**Comment by professor-mesmerize** [comment]
@StarrHelixx Good question! So I first came across it when I was testing out using Hydrus as a source on FlipFlip. I didn't have too many images in it yet so I just entered a URL like `http://localhost:45869/get_files/search_files?system_inbox=true`, rather than limit by a specific tag.

In practice, the main use case I see for this is when you just want to show _all_ images in your Hydrus inbox or archive. This use case is more common than one might think, specifically because the Hydrus Client API doesn't yet support "OR" functionality in the tags query param for the `get_files/search_files` endpoint yet - any tags included in that tag list are "AND"ed. So if I want to do a long FlipFlip session with every file I have in Hydrus, and I had to include the tags query arg, I'd have to manually add different Hydrus sources to FlipFlip for every single tag I have, which could be anything from annoying to nearly impossible depending on how many tags someone has.

Obviously, it'd help if Hydrus implemented "OR" functionality as well! But even then, being able to process a Hydrus source without tags would still be a lot easier than including every single the tags in the query args if you want to view all files. :)

For the record, I don't think this is a blocker to release of 3.1 or anything - just something to consider going forward!

**Comment by professor-mesmerize** [comment]
As always, thank you for the quick fix!

**Comment by StarrHelixx** [comment]
@professor-mesmerize Ok, I've adjusted the code to allow for URLs with _no_ tags: https://github.com/ififfy/flipflip/commit/f11b2d02f6be0854a6ec93cc3a07bf492b9b6341

I don't have a hydrus server available, so would you mind checking to see if a URL like the one you posted above actually works? (i.e. returns **all** images)

In response to your question about the `data.json` "corruption": It's not so much _corrupt_ as just stuck in an invalid state. Every time you load, it's trying to play a scene with that Hydrus source, which causes the regex to fail and then an ArrayOutOfBoundsException, and then FlipFlip barfs and shows the white page. I've tried in the past to create some kind of global wrapper that could serve an error page instead (and possibly allow user to reset or restore backup), but it didn't quite work. Possible I might be able to get it working in the future tho :+1:

**Comment by professor-mesmerize** [comment]
@StarrHelixx Apologies for the delay on this! I just tested on my local hydrus server by entering `http://localhost:45869/get_files/search_files` as a source, and it worked perfectly, thank you!

Also, thank you for indulging my curiosity on why we hit that particular error state! Definitely makes sense - there's always going to be limits on global exception handling.

**Comment by StarrHelixx** [comment]
Thank you for testing, I really appreciate it 😊
