### ISSUE TITLE
Ability to AutoStart scene at startup?

### ISSUE THREAD

**Issue by GenericPNP** [ififfy/flipflip#252]
If I have FlipFlip automatically open at Windows login, can I have it open a specific scene at startup? I'm planning to use this program in a kiosk-like display that runs Windows to slideshow through a library of videos and I would like the option to have a scene load automatically upon startup.

**Comment by StarrHelixx** [comment]
You can do this by running FlipFlip from the command line:

```
# cd wherever you've cloned FlipFlip into
cd flipflip

# Build the app
yarn install --dev
yarn build

# Start the app with a particular scene
yarn start '<Scene Name>'

# e.g.
yarn start "Cute Stuff"
