### ISSUE TITLE
Force Portrait or Landscape mode

### ISSUE THREAD

**Issue by slickmeister** [ififfy/flipflip#253]
It would be nice if there was an option to force everything to show in a certain aspect ratio.

Advanced mode would be to set a range, so that e.g. in a "Portrait scene", anything between 3:2 and 1:1 would show in its original orientation, but anything wider is rotated.

**Comment by StarrHelixx** [comment]
I also think it'd be good to include an option for filtering out images that aren't a specific orientation.

**Comment by StarrHelixx** [comment]
This is now implemented! https://github.com/ififfy/flipflip/commit/063bc2a10810189db014dda5671e8fc4545e260b

You can choose to force landscape/portrait or filter out images that aren't only landscape/portrait

**Comment by slickmeister** [comment]
Oh, I totally missed this! This works brilliantly, well done! 

You're right, the threshold option would be too much. As it is, FlipFlip is reaching the limit of how many options there are, imo. So I udnerstand your concern. More options would probably mean creating "scene templates" where standard scenes have the basic options, but allows users to make "Advanced scenes" where they can enable/disable the options that they want to use.

Amazing to have my feature implemented though, thank you so much!
