### ISSUE TITLE
How can I setup a Short Cut to start FlipFlip in a specific condition?

### ISSUE THREAD

**Issue by HarlowJW** [ififfy/flipflip#255]
I noticed that FlipFlip running in windows 10 will start in the condition that it shuts down in.  If it is shut down running a script (Alt+f4) it will start back up running that script.  Is this an artifact of windows or FlipFlip?  My experimentation points toward Windows but I have no real data to support that.  How can I setup a Short Cut to start FlipFlip in a specific condition so that a special build is not needed to start in a script?

**Comment by StarrHelixx** [comment]
FlipFlip stores it's current meta state in a file called `data.json`. When it is shut down and then restarted, it picks up the state file and continues with whatever it was doing last. This usually isn't a problem, but it sounds like you ran into a case where this was annoying. Can you be more specific about what you mean by "running a script"? Do you mean you had it like checking for offline files, you shut it down, and then when you start it back up, you'd prefer it not do that? There is not current way to do this, but if you can give me some more specific examples, it could be something I can add options for (or just ensure doesn't continue by default)

**Comment by slickmeister** [comment]
If I can chime in, I've had it happen several times that FlipFlip halts with a white screen while loading a scene, and I have to restore the app completely from a Backup. 

I feel like this could be solved by always starting FlipFlip in the main menu view. Or add a button in the title menu that offers an escape back to the main menu. Or if the app could detect this state of error, that would work too.

**Comment by StarrHelixx** [comment]
@slickmeister I added a whitescreen page which should catch any errors, and allows the user to (1) go back, (2) restore from backup, or (3) complete reset FlipFlip. This should alleviate a lot of that trouble.

As for this issue, closing until I hear back about specifics.
