### ISSUE TITLE
FlipFlip ignores inbox and archive query params in a search_files URL from the Hydrus API

### ISSUE THREAD

**Issue by floogulinc** [ififfy/flipflip#262]
Using a url like: 
```
http://localhost:45869/get_files/search_files?system_inbox=false&system_archive=true
```

FlipFlip will actually request:
```
http://localhost:45869/get_files/search_files
```
ignoring the desired filters

**Comment by professor-mesmerize** [comment]
Same thing happening on my instance as well.

**Comment by StarrHelixx** [comment]
I only have a rudimentary understanding of Hydrus functionality and use cases, so I had limited the filters to `tags=`, but code coulde be added to respect these other filters as well. Are `system_inbox` and `system_archive` the only other ones you'd like to see?

**Comment by floogulinc** [comment]
Since we are just providing a url also there is no UI for searching, it would probably be good to just accept any `search_files` url without caring about it's query params.
