### ISSUE TITLE
Caption scripts still don't seem to work in 3.1.4

### ISSUE THREAD

**Issue by spanner67** [ififfy/flipflip#283]
Further to the issue reported in #277 – I completely removed FlipFlip from my machine – both the Applications and Library folders. Then I installed a fresh, clean install of 3.1.4.

- I **can** load a script into the script library
- I **can't** load caption scripts into the Scripter tool, either from the local filesystem or the library
- I caption scripts added to a scene **are not** displayed

Here's a video of me trying, and failing, to make it work: https://share.getcloudapp.com/xQu6D96o

I'm on a Mac, Big Sur 11.3 (20E232)

**Comment by StarrHelixx** [comment]
@spanner67 Thank you very much for the detailed bug report! This bug has been fixed and will be included in the next release (aiming for 09/01)
