### ISSUE TITLE
Playback issues

### ISSUE THREAD

**Issue by xynosisx** [ififfy/flipflip#287]
![Screenshot (1)](https://user-images.githubusercontent.com/90482293/132922118-7145c3e3-acdd-4852-8259-decd43a43dbe.png)

Run into this error where I can't view source in grid layout properly, what gives?

**Comment by xynosisx** [comment]
I noticed the codec of the file is labelled as "built-in FFmpeg Decoder(h264, Thread Frame)" in PotPlayer and "Codec: H264 - MPEG-4 AVC" in VLC Player

**Comment by StarrHelixx** [comment]
(sorry for the v late response, just coming back to check on FlipFlip)

This looks like an encoding issue with the video file. Try using video editing software to re-encode the video and see if that fixes the issue
