### ISSUE TITLE
Console errors in 3.2.0 and loading slowly

### ISSUE THREAD

**Issue by Lapbunny** [ififfy/flipflip#289]
Hey, this is the peep on r/FlipFlip who had the slowdown in 3.2.0 - I'm seeing some console errors when trying to run, along with the images slowing down as the program runs. Not sure if there's anything more thorough I can provide, but figured I'd copy it over here.
[1631857843775.log](https://github.com/ififfy/flipflip/files/7182975/1631857843775.log)

Thanks!

**Comment by Lapbunny** [comment]
Actually apologies, I isolated it to the crossfade. No errors afterward and it's running hella smoother, aside from this one:

>Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22

**Comment by danapeleg55** [comment]
Doing god's work
