### ISSUE TITLE
Adding tracks into Audio Library does not always work for all mp3 files.

### ISSUE THREAD

**Issue by eyung71** [ififfy/flipflip#295]
i have a seemingly random issue with adding MP3s into the audio library. I can add new files, grab them from a folder and only certain files show up in my audio library.
Does anyone have this issue?
Does the audio have to be in a certain format to be acceptable?

**Comment by StarrHelixx** [comment]
You should be able to add a file to your Library as long as it's one of the following extensions: ".mp3", ".m4a", ".wav", ".ogg"

If this isn't working for a specific file, please provide the file (or even just filename) so I can help debug. You can also DM me on reddit if it is a sensitive title.

**Comment by katzlbt** [comment]
Files created with ...
`ffmpeg -i "$OUT" -vn -ac 2 -aq 5 -ar 22050 -f mp3 "$OUT2"`
cannot be added to the library. They contain ...

file:
`Audio file with ID3 version 2.4.0, contains:
 MPEG ADTS, layer III, v2,  56 kbps, 22.05 kHz, Stereo`

hexdump:
```
0000000 4449 0433 0000 0000 2300 5354 4553 0000
0000010 0f00 0000 4c03 7661 3566 2e38 3932 312e
```

The magic is odd. Would have expected 49 44 33 ???

Hope this helps.
