### ISSUE TITLE
Hid mouse setting

### ISSUE THREAD

**Issue by BrotherBolter** [ififfy/flipflip#298]
iv been using the program to stream in the background but the mouse keep being deplayed on-top no matter if it is moved to another desktop or no longer in focus
maybe a keybind would work or something

**Comment by StarrHelixx** [comment]
Mouse pointer seems to hide fine for me. Can you please provide more details for me to diagnose this issue?

What OS are you using?
Does this happen on _all_ scenes or just _particular_ scene(s)?
If it is only for certain scene(s), can you identify what unique setting might be causing this to happen?

**Comment by StarrHelixx** [comment]
I'm now noticing that the mouse only hides on the _main_ window (at least on Windows). I'm looking into this.

**Comment by BrotherBolter** [comment]
Hello sorry for the late response I've been using the program to make impromptu music videos streaming them on Discord but when I alt-tap to another program like a game or messing around in folders the cursor is still streamed in Discord and this is the only program that has this bug,
On windows FYI
