### ISSUE TITLE
SymLinks

### ISSUE THREAD

**Issue by musichypno** [ififfy/flipflip#303]
It appears that symlinks may not work in windows.

**Comment by StarrHelixx** [comment]
Sorry shortcuts in Windows are not symlinks and are not parseable by the [recursive readdir](https://www.npmjs.com/package/recursive-readdir) library FlipFlip uses. I also tried making a symlink using Windows' Linux sub-kernel, but that actually just ended up copying the directory, not linking it. 

Windows doesn't make linking directories easy like it is on Linux ... which is a shame.

**Comment by Wryyyong** [comment]
Hey, I get I'm probably a little late to this, but Windows NT _does_ have their own implementation of not just symlinks, but also hard links.

https://learn.microsoft.com/en-us/windows/win32/fileio/symbolic-links
https://learn.microsoft.com/en-us/windows/win32/fileio/hard-links-and-junctions

You can create any of the three manually via the Command Prompt's `MKLINK` builtin. Or if you want to be able to make them quickly and easily, there also exists [a shell extension](https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html) for that purpose. The extension also implements overlay icons for linked files and directories you can easily tell what's a link and what's not through File Explorer.
