### ISSUE TITLE
"Play after" option uses seconds instead of milliseconds

### ISSUE THREAD

**Issue by slickmeister** [ififfy/flipflip#305]
The Next Scene function has a very confusing behavior. I think it's the only instance in FlipFlip that uses seconds instead of milliseconds.

So it's very easy to type in 4000 when you want a 4 second timer. And then you scratch your head to find out why the scene isn't advancing.

I get that it should work for longer times where milliseconds become a bit unwieldy. But I still think it should behave in ms anyway by default.

**Comment by StarrHelixx** [comment]
This has been resolved on the `master` branch and will be included in the next release. Your existing scene and default configs will be automatically converted.
