### ISSUE TITLE
Scene level "script options" doesn't sync with Library

### ISSUE THREAD

**Issue by slickmeister** [ififfy/flipflip#311]
Is this intended behavior?

Once you've added a script to a scene, it no longer updates things like font, size and opacity if you change it in the Script Library. So you have to remove the script and add it again.

Am I missing something? Cause I can't get it to behave like I'd prefer. I get that you'd want the option to tweak scripts for particular scenes, but it feels like it should sync with the library by default and unlock the values only you change it manually.

**Comment by StarrHelixx** [comment]
I can definitely see how that was annoying. I've fixed it so that when you make a change in the Script Library to any particular script, it will propagate to that script in any of your Scenes

https://github.com/ififfy/flipflip/commit/6a9c1f921ba221294d8591a577c4c766079d37c7
