### ISSUE TITLE
Feature Request: Hotkey to blacklist and delete files without confirmation

### ISSUE THREAD

**Issue by 2CBAddict** [ififfy/flipflip#316]
Hello,

It would be wonderful to have the ability to blacklist files with a hotkey. 

Same thing for the delete but it would be very helpful to have a the ability to delete or blacklist files without pop-up confirmation as well.

Thank you!

**Comment by StarrHelixx** [comment]
This has been implemented here: https://github.com/ififfy/flipflip/commit/0da4bee7ba90c21aaaed4a5496d7c61cbf0e3818

The blacklist hotkey will be Ctrl+b (I will update the docs with this as well)
