### ISSUE TITLE
Dynamic speed control during playback

### ISSUE THREAD

**Issue by jflier23** [ififfy/flipflip#319]
It would be super neat to have two new hotkeys under 'Player Controls' that would allow the user to be able to increase the 'Scene Options'->'Timing' rate, i.e. increase/decrease speed by some fixed rate (i.e., 500 or 1000msec).

**Comment by StarrHelixx** [comment]
Hotkeys are already taken for this sort of thing ... this doesn't really flow well with how I expect FlipFlip to function. If you'd like an increasing/decreasing playback speed, try the Wave function
