### ISSUE TITLE
Feature Request: Delete moves to Recycle Bin

### ISSUE THREAD

**Issue by eros1ca** [ififfy/flipflip#321]
Current functionality is permanent deletion of files. Please give us the option to put it in the Recycle Bin in case of accidental deletion.

**Comment by StarrHelixx** [comment]
Looks like there is a library which can support this: https://github.com/sindresorhus/trash

I will give it a shot 👍

**Comment by StarrHelixx** [comment]
Sorry, this library seemed to have a problem with either React or Windows... I couldn't get it to work. So this is going to be a wontfix option for me
