### ISSUE TITLE
Scenes don't wrap

### ISSUE THREAD

**Issue by LeChninkel** [ififfy/flipflip#39]
Hey there ! 
first of all, congratulations for the work done ! Wow... the latest release is absolutely great, and I love the new UI improvements on the Scenes selection. However, I already have like 20 scenes predefined, and it means I need to scroll horizontally to get to the last ones. A grid approach with a sort of dynamic tiling would maybe be more convenient ? But that's just me being picky... ;-)
At any rate, I LOVE the new options, and I'm having so much fun tweaking and creating my perfect scenes. Thank you so much for this awesome piece of software !  :-) 
Keep up the good work!!!

**Comment by ififfy** [comment]
LOL I thought they would wrap! I'll fix it now. :-)

**Comment by ififfy** [comment]
Check the release page when this comment is 10 minutes old for 1.1.3.
