### ISSUE TITLE
Load images from remote locations

### ISSUE THREAD

**Issue by ififfy** [ififfy/flipflip#4]
It's pretty unlikely that I will personally make this happen, but I would love to accept contributions.

**Comment by ififfy** [comment]
Note for anyone looking into it: the way FlipFlip is written, this is both easy and hard.

Easy because the app is already written to expect images to load asynchronously (it actually loads 5 at a time and shows the first one that's available).

Hard because once you try to access the network, Electron (I think??) locks itself down and stops letting you call node.js APIs willy nilly, which the app does A LOT right now. You'll probably need to move all the `fs`, `path`, and `recursive-readdir`-using code into `main.ts` and write some bridging code so that the renderer can still use that stuff.

**Comment by GoddessServant0** [comment]
I do plan on working on this 👍 

> Hard because once you try to access the network, Electron (I think??) locks itself down and stops letting you call node.js APIs willy nilly, which the app does A LOT right now. You'll probably need to move all the fs, path, and recursive-readdir-using code into main.ts and write some bridging code so that the renderer can still use that stuff.

I'm making network requests for hastebin text already and I don't seem to be experiencing this behavior yet 🤔 Would Electron (or w/e) behave differently for a stream response vs plain text?

**Comment by ififfy** [comment]
Fortunately, you're probably right and I was worried for no reason.

**Comment by ififfy** [comment]
Just to add some more info to what I was thinking: the simplest thing would be to support a text file of URLs. Very easy to create and distribution, no hairy integrations with APIs at this point.

**Comment by ififfy** [comment]
Fixed by #33
