### ISSUE TITLE
Show file info somehow (when paused)

### ISSUE THREAD

**Issue by GoddessServant0** [ififfy/flipflip#42]
Would be nice if you could see some info about the current file being shown.

Maybe this happens on mouse over, or even right click? Or could be up in the control bar.

Possibly a delete option. I often come across pictures that I'd rather just remove from FlipFlip.

**Comment by ififfy** [comment]
This is exactly what I had in mind when I put the `historyPaths` state key into `ImagePlayer`. It actually contains URLs now (so it should be renamed...) but there's probably a handy JS library to convert file:// URLs back to path strings.

**Comment by ififfy** [comment]
Or you could just peek at the `img.src` value :-)

**Comment by GoddessServant0** [comment]
This was addressed by #55
