### ISSUE TITLE
Allow display options to change while playing

### ISSUE THREAD

**Issue by GoddessServant0** [ififfy/flipflip#46]
After waiting for a large set to load, it'd be nice not to have to hit back to make a change to the zoom level, text overlay, transition rate, etc. (and then having to reload all images again)

It'd be nice to have the ability to change these options while the slideshow is playing (perhaps a mouseover sidebar)

**Comment by ififfy** [comment]
The steps are pretty simple to make this happen, at least for timing and effects:

* `Player` takes an argument `onUpdateScene`, just like `SceneDetail` does
* Move "Timing" and "Effects" sections into their own components
* Add them to `Player`

The gif filter wouldn't work or would need to be changed. Audio is a maybe, but HTML5 audio is finicky. Text might also be doable.

**Comment by GoddessServant0** [comment]
This was addressed in #58. Leaving this issue open until "Timing" and "Effects" are put in their own elements (to reduce redundancy and keep forms consistent)

**Comment by GoddessServant0** [comment]
Addressed in #60
