### ISSUE TITLE
Spiral overlay

### ISSUE THREAD

**Issue by ififfy** [ififfy/flipflip#5]
SVG animated by CSS?

**Comment by GoddessServant0** [comment]
Isn't what people _really_ want is to be able to overlay one Scene on another? Instead of being limited to "spiral" you have control of every aspect of both layers, and control of opacity. What do you think? Haven't 
 fully delved into how images are processed, so wasn't sure if this is feasible.

**Comment by ififfy** [comment]
I honestly think a lot of people literally just want a spiral.

The way React works, overlaying scenes should be pretty easy. You just have `Player` create a second `ImagePlayer`, and pass all scene objects down to `Player` so it's able to look up the second scene.

**Comment by GoddessServant0** [comment]
This has been implemented through scene overlay
