### ISSUE TITLE
Let scenes transition to other scenes on a timer

### ISSUE THREAD

**Issue by ififfy** [ififfy/flipflip#6]

**Comment by ififfy** [comment]
I think I want to do this using a totally separate data structure, with its own separate editor and player. Something like this:

```ts
class Timeline {
  entries: Array<TimelineEntry>;
}

class TimelineEntry {
  sceneID: string;
  seconds: number;
}
```

**Comment by ififfy** [comment]
OTOH, this would be really simple to do in the same style as overlay scenes, with a string field and a dropdown.

**Comment by GoddessServant0** [comment]
This was implemented https://github.com/ififfy/flipflip/commit/f67182949f535314a5f0c8a662bba6f5b0e76083
