### ISSUE TITLE
Bundles

### ISSUE THREAD

**Issue by ififfy** [ififfy/flipflip#68]
It would be nice if you could bundle up images and scene settings into a zip file that could be shared over the internet.

**Comment by ififfy** [comment]
Here's how I recommend doing this.

BTW, I'm doing all these "here's how I would do this" responses to cover the likely scenario where I don't personally get around to it, but I'm always happy to answer questions.

# Export

The scene detail screen should have an "export bundle" option. It works like this:

1. Have the user pick a place to save the JSON file
2. For all local sources, convert the absolute file URLs so they are instead relative to the JSON file.
3. Save the scene as JSON with the converted URLs.

So here's your original scene:

```js
{
  directories: [
    "file:///Users/ififfy/flipflip/puppies/cuddling",
    "file:///Users/ififfy/flipflip/puppies/running",
  ],
  /* everything else */
}
```

Then you save the bundle at `/Users/ififfy/flipflip/puppies/bundle.flipflip`. The JSON that gets written out is:

```js
{
  directories: [
    "file://cuddling",
    "file://running",
  ],
  /* everything else */
}
```

# Import

Add a new field `Scene.directoryRoot`, which is the path all local directories are relative to. If this value is present, all paths (including audio?) should be joined with it.

Copy the `this.isRoute('scene')` conditional from `Meta.render()` and change it to `this.isRoute('bundleScene')`. Inside it, pass `this.state.bundleScene` instead of `this.scene()`.

At this point you can do the actual import with a button callback or something:
* Load the JSON file that the user selects
* Create a scene from it, just like we do on initial data load, but also set `scene.directoryRoot` to the file's parent directory path
* Store it in `this.state.bundleScene`
* `this.setState({route: [new Route({kind: 'bundleScene', value: nil})]});`

# Distribution

Put all the images you want to use in the same directory, add them to a scene, export it, zip, and upload! :-)

**Comment by GoddessServant0** [comment]
@f3lin3 Maybe take a swing at this if you think you're up to it 😉

**Comment by GoddessServant0** [comment]
This was done in a very rudimentary way. 2b8157f45a86383b2b7f18d7a7fa4ea73cdb5602

I messaged the few people on Reddit who specifically asked for this and inquired if they were expecting local files to work. The consensus was that would be nice, but, ultimately an export/import of remote sources was sufficient.

This implementation simply exports the JSON representation of a scene and import creates a new object with it ¯\_(ツ)_/¯

When a Scene is imported, we make sure we create a unique ID, but everything else is maintained.  I debated if I should also clear the overlay settings, as they will not be pointing to the correct Scene (as ID's will surely differ).

**Comment by f3lin3** [comment]
Good grief - well done - I only recently noticed that you mentioned me 13 days ago on this thread as being something I could take a swing at... So sorry.  

BTW: Which Reddit groups should I be tracking to keep up with this?

F3

**Comment by GoddessServant0** [comment]
Hey no problem! I'm not too used to Git's social platform. I was hoping it would notify you guys if I tagged you (like on Reddit), but don't think it does that.

Just /r/flipflip. But there's not a lot of activity. Mostly been used as release notices. I also post to a few other communities (I'll refrain from mentioning here 😏)
