### ISSUE TITLE
Re-order SceneDetail to show Sources under scene effects?

### ISSUE THREAD

**Issue by GoddessServant0** [ififfy/flipflip#72]
So I was wondering if you were ok with moving "Sources" underneath the other `ControlGroup`s in `SceneDetail`. 

Right now, if you have a Scene with a lot of sources, you have to scroll _down_ to get to scene effects. This seems like a poor user experience. 

If we move "Sources" to the bottom, we could also move the remove/add buttons to the top of the element, making the user do as little work as possible to reach all actions.

**Comment by ififfy** [comment]
Yes, and while you're at it, please disable the Play button until there is at least one source.
