### ISSUE TITLE
Notify user of new FlipFlip version within app

### ISSUE THREAD

**Issue by GoddessServant0** [ififfy/flipflip#75]
Would be cool if FlipFlip could "Check for Updates..." and automatically update if new release is available.

Not exactly sure how to implement this, but will look into

**Comment by ififfy** [comment]
It's pretty hairy. I don't want to start serving the client JS from the web, and dealing with local updaters is very different across platforms.

**Comment by GoddessServant0** [comment]
Rather than actually _update_ from the app, what about checking the release feed and notifying users if there's a new version and directing them here?

**Comment by GoddessServant0** [comment]
I went ahead and added a quick check which alerts users to new version! This will be rolled out with 2.0

Implemented 291da8e78edb1de660052ea000a4988ac58fab57
