### ISSUE TITLE
Remote Sources

### ISSUE THREAD

**Issue by GoddessServant0** [ififfy/flipflip#76]
- [x] First, the framework will need to be slightly modified so that allURLs can be asynchronously appended to.

Sources to Implement:
- [x] Tumblr
- [x] Reddit

We can use [RipMe](https://github.com/RipMeApp/ripme) as as reference for code to scrape these sites if needed.

**Comment by GoddessServant0** [comment]
I've made the initial changes and pushed a new branch [v2.0_Work](https://github.com/ififfy/flipflip/tree/v2.0_Work)

* I modified the directory loop in `HeadlessScenePlayer` to use a single method for choosing what to do with a source URL.
* I implemented a function for creating promises for the Tumblr API.
  * Just put in my API key for now, we may want to make this configurable, but it may not really be an issue (gooninator2 uses a single API key 🤷‍♀️)
  * I tested a number of different Tumblr blogs and seemed to be able to parse all the images either from `posts.photos.original_size.url` or `posts.body`, but there may be other cases I didn't find while testing.
* I modified `CancelablePromise` to be a data-holder for looping sources.
* I added a queue of promises to HSP
* I implemented a promise loop to properly parse through sources and add images to the correct array index
* Fixed issue with `gifInfo` when using remote gifs (need to read into `ArrayBuffer` object for `gifInfo` to work)
  * Added `request` library, but another could be used. I tried to find a way to do this with `wretch` but couldn't find a way to read a url into a buffer
* Fixed some odd behavior with the loading indicators, progress message, and empty indicator
  * This could still be improved. If you are loading from a tumblr and have the "Only gifs" filter active, the progress bar disappears when the source has loaded, but you may not actually encounter an animated gif for many pages.

**Comment by ififfy** [comment]
One thing to look out for is how the image loading queue interacts with the remote source loading queue, and whether it causes any weird side effects in the player. Gooninator would behave weirdly if you had a long delay (~10s) where it would load 100 images really quick from the first tumblr API page, and then show them to you really slowly, so it would take ages to see a wider variety.

**Comment by GoddessServant0** [comment]
Reddit works now! 😁
