### ISSUE TITLE
Install on a Mac - nothing happens after right click Open

### ISSUE THREAD

**Issue by eyung71** [ififfy/flipflip#77]
Downloaded Mac version 1.2.0.
Unzipped file. 
Right click FlipFlip and Open. 
I get one box that asks me to confirm if I want to open it for my security settings.
I click okay.
Nothing happens. No icon. Doesn't show up as an open program on my Force Quit list.

**Comment by GoddessServant0** [comment]
Was able to replicate, probably was an issue from me doing the release from a Windows machine. Fixed Mac OS Release

**Comment by eyung71** [comment]
Thank you! I've downloaded the new MacOS release and it works wonderfully. thank you!
