### ISSUE TITLE
Remove Sources - Bug

### ISSUE THREAD

**Issue by f3lin3** [ififfy/flipflip#80]
In Scene Detail - if the same (local) folder is added more than once - when trying to delete any of the duplicates by clicking the red 'X' button rather than removing just the selected entry it removes all copies of the same folder.

(Enhancement suggestion - it would be helpful if the source paths could be editable other than through a directory picker).

**Comment by GoddessServant0** [comment]
🤔 Should have prevented a duplicate dir from being added in the first place, I'll take a look

As for enhancement -- do you mean like directly edit the text of a source? Makes sense to me, just wanted to make sure I understood.

**Comment by f3lin3** [comment]
Yes - was thinking to be able to directly edit the text of the source path directly - (possibly to use cut and paste too.)  However, the difficulty or issue I see with it though is how to handle cleanly the exception if the directory path does not actually exist - using the directory picker for now - currently limits that problem.

**Comment by ififfy** [comment]
The source of the bug is pretty obvious. The "remove" button filters all values out of the list that match the one you picked. I had just assumed people wouldn't add duplicates >_>

**Comment by GoddessServant0** [comment]
Looks like I accidentally removed this 7cfcffb. Fixed this in b252d26.
