### ISSUE TITLE
Is the @font-face rule in style.scss working as expected?

### ISSUE THREAD

**Issue by f3lin3** [ififfy/flipflip#83]
I am making the binaries on a Debian 9 system, and seeing significant differences between the Windows and Linux rendering of text in the app.   Fundamentally it appears that the Windows binaries display using a Sans Serif type of font - pretty much like the screenshots in the doc_images folder.

However, the Linux builds all seem to use a Serif type of font for example: 
![screenshot from debian 9 x64](https://user-images.githubusercontent.com/46749380/51430547-e9444580-1c14-11e9-82b3-f26014776ba9.png)

It seems no matter what I play around with in the @font-face rule in style.scss nothing changes....

However, if I change the font-family attribute in the body class to "system-ui"  then builds for the Linux and Windows platforms all appear to display San Serif type fonts - although there is a slight difference in appearance for Windows from when the attribute is set to "system".   

What makes me question further if the @font-face rule actually is doing anything is that changing the font-family attribute from "system" (around line 20) to "system-ui"  appears to make no impact.

Any tips, pointers, suggestions of things to try?

If others can replicate this should / could the font-family attribute in the body element (line 36 style.scss) be changed to "system-ui" for the time being to give a more consistent look between the different platform versions?

**Comment by ififfy** [comment]
`font-face` is for defining values that can be used in `font-family`. By changing the name, you're simply removing the font declaration everywhere.

What you really need to do is find an appropriate value to add to the `src` attribute that matches a commonly installed font on Linux systems.

**Comment by ififfy** [comment]
Put another way, it looks like the font list isn't finding something on your system:

```
local(".SFNSText-Light"),
local(".HelveticaNeueDeskInterface-Light"),
local(".LucidaGrandeUI"),
local("Ubuntu Light"),
local("Segoe UI Light"),
local("Roboto-Light"),
local("DroidSans"),
local("Tahoma");`

**Comment by f3lin3** [comment]
This issue can be closed if https://github.com/ififfy/flipflip/pull/84 can be pulled. Thanks for the explanation and patience to explain how to resolve it.
