### ISSUE TITLE
What to do about remote source timeouts

### ISSUE THREAD

**Issue by GoddessServant0** [ififfy/flipflip#85]
Tumblr (and any other remote source) impose request limits to prevent remote API users from overloading the system. Tumblr's limits are: 1,000 requests per hour, 5,000 requests per day (however, it's definitely not this literal). If you exceed this limit, the Tumblr API simply starts returning 429 (Too Many Requests).

I want to keep the timeout between requests as low as possible so images can be served quickly, but also want to prevent getting 429'd (which means Tumblr sources would be useless until the time cap has passed).

I did some extensive testing and found that an 8 second timeout worked for a scene with no overlay... but once you add an overlay, even a 16 second delay results in 429 after only 40 minutes. 😢

So... that leaves me to think we should add a limit to the number of pages processed per source. That way, we can serve the sources quickly and prevent getting soft banned by Tumblr. Considering some blogs have 100k's of images, it doesn't make sense to keep querying forever. **What do we think about 20 pages?** More/less?

**Comment by f3lin3** [comment]
Is the solution to this to consider caching?   Say for example the user selects a remote source to import should we not also give the user the option of specifying a local folder to map the remote source to? (the local file name defaulting to the domain and sub domain name of the remote site).

If a user selects to import from a remote site - then at whatever throttled rate of querying of the site you / we determine optimal so as not to hit 429 or other remote system errors is the rate at which the images are queried and stored locally.  The images displayed in FlipFlip could then come from the local folder.  If 429 or other error is encountered then the import is stopped until the next time a user selects to play the scene.   However the user still gets to see the local images which have been downloaded so far to date.  The next time the user selects Play of that scene - the import attempts to continue but does not download to add to the cache of that remote source any of the files it already has. 

In that way the user can create and build up a local library that maps to the remote server and does not request files it has already downloaded?

**Comment by ififfy** [comment]
If you're hitting rate limits, you should use a central queue object (one per API: so one queue for all of Tumblr) and enqueue/dequeue stuff on it from each individual player. Caching would be a nice optimization.

```typescript
class TumblrQueueItem {
  sourceID: string  // name of blog
  url: string  // paging URL from the API
  callback: function
}

class TumblrQueue {
  queue: TumblrQueueItem[]
  isRunning = false

  enqueue(sourceID: string, url: string, callback: function) {
    this.queue.push(TumblrQueueItem(sourceID, url, callback));
    if (!this.isRunning) this.run();
  }

  run() {
    if (!this.queue.length) {
      this.isRunning = false;
      return;
    }
    const item = this.queue.pop();
    // a simple caching strategy would be for makeTumblrAPIRequest() to store a simple
    // on-disk mapping of URL -> response text to keep the implementation details out
    // of the queue.
    makeTumblrAPIRequest(item).then((results) => {
      item.callback(results);
      setTimeout(this.run.bind(this), RATE_LIMIT);
    });
  }
}

// anything that needs to load a tumblr API thing should use
// TUMBLR_QUEUE.enqueue(...)
// instead of using the API directly.
const TUMBLR_QUEUE = new TumblrQueue();
```

**Comment by GoddessServant0** [comment]
Caching was _definitely_ a solution I was considering, though I was thinking I'd implement this a little later. I might just put a temporary limit in place until caching is added, but that's the ultimately goal.

Thanks for the help!

**Comment by GoddessServant0** [comment]
Caching has been fully implemented (both storage and retrieval) just need to allow user to configure
