### ISSUE TITLE
Rounded Styling?

### ISSUE THREAD

**Issue by f3lin3** [ififfy/flipflip#89]
I have for fun played around with the style.scss file to create a more rounded look and feel.

Attached here are some examples - Should I create a PR for these or are square corners the preferred ui?
![round button styling 1](https://user-images.githubusercontent.com/46749380/51853119-711a0600-231f-11e9-9e8a-f0781d5d34e1.png)
![rounded control groups 1](https://user-images.githubusercontent.com/46749380/51853249-bf2f0980-231f-11e9-92bd-419728aa8c38.png)

**Comment by GoddessServant0** [comment]
Personally, I prefer the square corners, but I really think we are starting to get into the realm of environment customizations. I'm sure some people would prefer a choice in Theme.

I feel like this would be a great option to include in a general "FlipFlip Settings" form, along with some other possible settings. When caching is introduced, specifying caching dir and limiting space in disk would also be good to put there.

**Comment by ififfy** [comment]
The style is meant to be a callback to an extinct operating system from the '90s called BeOS.

[Screenshots](https://guidebookgallery.org/screenshots/beos5)

As the creator of this app, I reserve the privilege to make poor aesthetic design decisions. 😄 If someone puts in a lot of time on a total redesign, AND their CSS is maintainable, only then will I consider merging visual changes like this.

**Comment by ififfy** [comment]
Themes would also be OK if someone wants to put in the time, but compared to all the other potential features, it has the lowest imaginable priority, since it doesn't actually help anyone do anything new.

**Comment by ififfy** [comment]
(I _would_ accept pull requests that make it look _more_ like BeOS.)
