### ISSUE TITLE
Bug?  "+ Add Local Files" in SceneDetails 

### ISSUE THREAD

**Issue by f3lin3** [ififfy/flipflip#93]
Clicking on the +Add local files button on Scene Details permits the button to be repeatedly pressed multiple times launching multiple copies of the Directory Picker.  Surely after a single click the button should not accept further clicks until the Directory Picker has been closed?

This 'feature' affects - Linux 32, Linux 64 and Windows Builds - no idea about Mac.

**Comment by GoddessServant0** [comment]
This issue was fixed in the commit above ^^ It will be included in 2.0.
