### ISSUE TITLE
Save Window State

### ISSUE THREAD

**Issue by f3lin3** [ififfy/flipflip#94]
I would like to add some functionality to save the running state of the Electron Browser Window (Size, Screen Location, menu visibility etc).  Given that the existing functionality is that if the app is closed when it is running when it next launches the app continues on from where it was, but resets the window size, location and menus back to the defaults.

The proposed code changes required are likely to be in Meta.tsx  ... but I note that some work is taking place in Meta.tsx on the v2.0_Work branch....

Should I make proposed changes to the master branch or to the v2.0_Work branch?

**Comment by GoddessServant0** [comment]
Yes! Please do work against v2.0 unless it's a bug that needs immediate fixing. It'd also be good to familiarize yourself with some of the changes I made. Shouldn't be anything too major, did some re-jiggering, but mostly just additions. If you have any questions, please feel free to ask 😁

**Comment by GoddessServant0** [comment]
This is done 👍 😄 cf3110db79d5dcd9d2407050eb28c48a4a37721e

**Comment by f3lin3** [comment]
Great solution.
