### ISSUE TITLE
Random Scene?

### ISSUE THREAD

**Issue by LeChninkel** [ififfy/flipflip#95]
just thought it would be nice to have a "I feel lucky" button in the Scenes tile page. Just for when I am too bored to pick a scene and just want to be surprised.
Also, I am starting to get a significant number of scenes in my FlipFlip... an alphabetical sorter would be great? 😃

**Comment by GoddessServant0** [comment]
Thanks for the feature request! A random button and ability to sort (and drag'n'drop) has been implemented in v2.0! Expect a beta release sometime in the next week or so 👍

**Comment by LeChninkel** [comment]
Oh joy !! 😄
