### ISSUE TITLE
User Config

### ISSUE THREAD

**Issue by GoddessServant0** [ififfy/flipflip#96]
I've finally finished my implementation of the Library (and many other general improvements) and thought another great feature for 2.0 would be a general user config we can use throughout FlipFlip!
This would be a new form accessible from the home (`ScenePicker`) and would modify a config object in `Meta` with a group of keys.

- [x] Implement config route and object and form
- [x] Use config

Possible configs:
- [x] Default Scene settings (These would be used any time a new Scene is created)
- [x] Enable Caching
- [x] Caching dir (when implemented)
- [x] Caching dir max size
- [x] API Keys (e.g. Tumblr)
- [x] Text overlay font (fontface, style, weight, size, color, etc.)

**Comment by GoddessServant0** [comment]
This was implemented in b1006e5fdfc4970cc3c77336dd50f004edf0e500
Still need to actually make config do something and add other config options

**Comment by f3lin3** [comment]
Great work
